### PR TITLE
Start AudioSwitchManager only when audio track added (fix #1163)

### LINKED ISSUE #1163: Android: Webrtc initializing audio services even in datachannel-only apps
**Describe the bug**
When I'm open a peer connection with data channel only. Android plugin is initaizing AudioSwitchManager etc. Which not required.
Following logs are observed.
```
I/org.webrtc.Logging(28618): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
I/org.webrtc.Logging(28618): WebRtcAudioEffectsExternal: setAEC(true)
I/org.webrtc.Logging(28618): WebRtcAudioRecordExternal: enableBuiltInNS(true)
I/org.webrtc.Logging(28618): WebRtcAudioEffectsExternal: setNS(true)
I/AudioManager(28618): In startbluetoothSco(), calling application: com.example.android
I/AudioManager(28618): In startbluetoothSco(), calling application: com.example.android
I/AudioManager(28618): In startbluetoothSco(), calling application: com.example.android
I/AudioManager(28618): In startbluetoothSco(), calling application: com.example.android
I/AudioManager(28618): In setSpeakerphoneOn(), on: true, calling application: com.example.android
W/FlutterWebRTCPlugin(28618): audioFocusChangeListener [Speakerphone(name=Speakerphone), Earpiece(name=Earpiece)] Speakerphone(name=Speakerphone)
...
```
This also caused connected devices to stuck in calling mode, even when the connection is closed.

**To Reproduce**
Create a peer connection with data channel only.
```
    _peerConnection = await createPeerConnection(_configuration, _constraints);

    _sendChannel = await _peerConnection?.createDataChannel("sendChannel", RTCDataChannelInit());
```
**Expected behavior**
Should not do any audio initilization.

**Platform information**

* **Flutter version**: : 3.3.4 
* **Plugin version**: 0.9.12
* **OS**:  Android
* **OS version**: 11

### PR DESCRIPTION
**Pull request by rostopira**

### CODE REVIEW

File: android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java [hunk 1]
```diff
@@ -465,6 +457,10 @@ public void onAddTrack(RtpReceiver receiver, MediaStream[] mediaStreams) {
           trackInfo.putBoolean("remote", true);
           params.putMap("track", trackInfo.toMap());
           sendEvent(params);
+
+          if ("audio".equals(track.kind())) {
```
Comment (cloudwebrtc) [inline android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java:461]: I have a question, when execute getUserMedia, a local audioTrack is created, should we also call `AudioSwitchManager.instance.start();`? In my memory, `onAddTrack/onTrack` should be triggered after the remote stream arrives.

Comment (rostopira) [reply android/src/main/java/com/cloudwebrtc/webrtc/PeerConnectionObserver.java:461]: My first thought was, that it's used only for output control, missed that, will fix
